version: 0.2

phases:
 phases:
        install:
         runtime-versions:
         docker: 18 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-central-1 --no-include-email)
      - REPOSITORY_URI=${repository_url}
      - echo $REPOSITORY_URI
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $IMAGE_TAG
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg environment="test" -t 217577495775.dkr.ecr.eu-central-1.amazonaws.com/empatica-registry:latest .
      - docker tag 217577495775.dkr.ecr.eu-central-1.amazonaws.com/empatica-registry:latest 217577495775.dkr.ecr.eu-central-1.amazonaws.com/empatica-registry:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 217577495775.dkr.ecr.eu-central-1.amazonaws.com/empatica-registry:latest
      - docker push 217577495775.dkr.ecr.eu-central-1.amazonaws.com/empatica-registry:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"web","imageUri":"%s"}]' 217577495775.dkr.ecr.eu-central-1.amazonaws.com/empatica-registry:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json